[gemini]
api_key = "YOUR_GEMINI_API_KEY"
model = "gemini-1.5-flash"

[firebase]
api_key = "YOUR_FIREBASE_API_KEY"
auth_domain = "YOUR_FIREBASE_AUTH_DOMAIN"
project_id = "YOUR_FIREBASE_PROJECT_ID"
storage_bucket = "YOUR_FIREBASE_STORAGE_BUCKET"
messaging_sender_id = "YOUR_FIREBASE_MESSAGING_SENDER_ID"
app_id = "YOUR_FIREBASE_APP_ID"